name: ✨

on:
  workflow_dispatch:

jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      
      - run: |
          echo "Updated At: $(date "+%d-%m-%y %T")" > README.md
          git config --global user.name DC
          git config --global user.email "clonebmn2itt+1@gmail.com"
          git add .
          git commit -m "feat: update code"
          git push origin HEAD
      
      
          

