name: ✨

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'
  # push:
  #   branches: 
  #     - main

jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      
      - run: |
          git config --global user.name DC
          git config --global user.email "clonebmn2itt+1@gmail.com"
          echo "Updated At: $(date "+%d-%m-%y %T") 1" > README.md
          git add .
          git commit -m "feat: update code"
          echo "Updated At: $(date "+%d-%m-%y %T") 2" > README.md
          git add .
          git commit -m "feat: update code"
          echo "Updated At: $(date "+%d-%m-%y %T") 3" > README.md
          git add .
          git commit -m "feat: update code"
          echo "Updated At: $(date "+%d-%m-%y %T")" > README.md
          git add .
          git commit -m "feat: update code"
          git push origin HEAD -f
      
      
          

